### ISSUE TITLE
Bug in ipc_absindex()

### ISSUE THREAD

**Issue by oranego** [siffiejoe/lua-luaipc#7]
In file ipc.c, function ipc_absindex(L,idx), the line should be
    idx += lua_gettop( L ) + 1;
instead of:
    idx += lua_gettop( L );

e.g. index -1 should be top of stack, not one below top.

(The problem I was having was that shm wasn't unlinking after close.
After some digging around, I uncovered this bug.)

**Comment by siffiejoe** [comment]
You are very right. Thanks!
